from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
import os

def set_cell_border(cell, **kwargs):
    """
    Set cell border helper
    Usage: set_cell_border(cell, top={"sz": 12, "val": "single", "color": "#FFD700"})
    """
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    for side in ('top', 'left', 'bottom', 'right'):
        if side in kwargs:
            tag = 'w:{}'.format(side)
            element = tcPr.find(qn(tag))
            if element is None:
                element = OxmlElement(tag)
                tcPr.append(element)
            for key, val in kwargs[side].items():
                element.set(qn('w:{}'.format(key)), str(val))

async def generate_manual(run, steps):
    doc = Document()
    
    # 1. Cover Page
    doc.add_paragraph("\n" * 5)
    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_run = title.add_run("AUTOMANUAL AI")
    title_run.font.size = Pt(48)
    title_run.font.bold = True
    title_run.font.color.rgb = RGBColor(10, 25, 47) # Navy
    
    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub_run = subtitle.add_run("Autonomous Software User Guide")
    sub_run.font.size = Pt(18)
    sub_run.font.italic = True
    sub_run.font.color.rgb = RGBColor(212, 175, 55) # Gold
    
    doc.add_paragraph("\n" * 3)
    info = doc.add_paragraph()
    info.alignment = WD_ALIGN_PARAGRAPH.CENTER
    info_run = info.add_run(f"Project URL: {run.url}\nGeneration Date: {datetime.now().strftime('%B %d, %Y')}")
    info_run.font.size = Pt(11)
    info_run.font.color.rgb = RGBColor(100, 100, 100)
    
    doc.add_page_break()
    
    # 2. Table of Contents (Placeholder logic)
    doc.add_heading("Table of Contents", level=1)
    doc.add_paragraph("1. Overview")
    doc.add_paragraph("2. Step-by-Step Exploration")
    doc.add_paragraph("3. Technical Source Mapping")
    doc.add_page_break()
    
    # 3. Overview
    doc.add_heading("Overview", level=1)
    doc.add_paragraph(
        f"This manual was autonomously generated by AutoManual AI. "
        f"Our agent explored '{run.url}' using visual reasoning and mapped UI actions "
        f"to the associated source code repositories."
    )
    
    # 4. Steps
    for i, step in enumerate(steps):
        doc.add_heading(f"Step {step.step_number}: {step.description or step.action}", level=2)
        
        # Step Details Table
        table = doc.add_table(rows=1, cols=2)
        table.autofit = True
        cells = table.rows[0].cells
        
        # Action & Reasoning
        p = cells[0].add_paragraph()
        p.add_run("Action: ").bold = True
        p.add_run(f"{step.action}\n")
        
        if step.ai_reasoning:
            p.add_run("AI Logic: ").bold = True
            p.add_run(step.ai_reasoning).italic = True
            
        # URL
        p.add_run(f"\nURL: {step.url}").font.size = Pt(8)
        
        # Screenshot
        if step.screenshot_path and os.path.exists(step.screenshot_path):
            try:
                cells[1].paragraphs[0].add_run().add_picture(step.screenshot_path, width=Inches(3))
            except:
                cells[1].text = "[Image Error]"
        
        # 5. Source Code Mapping (The "Product" differentiator)
        doc.add_heading("Technical Source Mapping", level=3)
        code_box = doc.add_table(rows=1, cols=1)
        code_box.style = 'Table Grid'
        code_cell = code_box.rows[0].cells[0]
        code_cell.paragraphs[0].text = step.mapped_code or "// No source mapping available for this step."
        # Set a grey background and monospaced font for code
        shading_elm = OxmlElement('w:shd')
        shading_elm.set(qn('w:fill'), "F4F4F4")
        code_cell._tc.get_or_add_tcPr().append(shading_elm)
        
        # doc.add_page_break()
        doc.add_paragraph("\n")
        
    # Output
    os.makedirs("storage/docs", exist_ok=True)
    output_path = f"storage/docs/{run.id}.docx"
    doc.save(output_path)
    return output_path

from datetime import datetime
